main: ${project.groupId}.${project.name}
name: ${project.name}
version: ${project.version}
website: ${project.url}
description: ${project.description}
authors: [Cayorion]
depend: [MassiveCore]
permissions:
# -------------------------------------------- #
# THE REAL NODES
# -------------------------------------------- #
  creativegates.create: {description: create a gate, default: false}
  creativegates.use: {description: use a gate, default: false}
  creativegates.cg: {description: use creativegates base command, default: false}
  creativegates.cg.world: {description: world gate management, default: false}
  creativegates.cg.world.list: {description: gate count per world, default: false}
  creativegates.cg.world.delete: {description: delete all gates in world, default: false}
  creativegates.cg.config: {description: edit configuration, default: false}
  creativegates.cg.lang: {description: edit language configuration, default: false}
  creativegates.cg.version: {description: see plugin version, default: false}
# -------------------------------------------- #
# STAR NOTATION
# -------------------------------------------- #
  creativegates.*:
    default: false
    children:
      creativegates.create: true
      creativegates.use: true
      creativegates.cg: true
      creativegates.cg.world: true
      creativegates.cg.world.list: true
      creativegates.cg.world.delete: true
      creativegates.cg.config: true
      creativegates.cg.lang: true
      creativegates.cg.version: true
# -------------------------------------------- #
# KITS
# -------------------------------------------- #
  creativegates.kit.op:
    default: op
    children:
      creativegates.*: true
  creativegates.kit.rank3:
    default: false
    children:
      creativegates.kit.rank2: true
      creativegates.cg.config: true
      creativegates.cg.lang: true
  creativegates.kit.rank2:
    default: false
    children:
      creativegates.kit.rank1: true
  creativegates.kit.rank1:
    default: false
    children:
      creativegates.kit.rank0: true
      creativegates.cg: true
      creativegates.cg.world: true
      creativegates.cg.world.list: true
  creativegates.kit.rank0:
    default: false
    children:
      creativegates.cg: true
      creativegates.cg.version: true
  creativegates.kit.default:
    default: true
    children:
      creativegates.kit.rank0: true
